packaging_format = 2

id = "shiori"
name = "Shiori"
description.en = "Simple bookmark manager"
description.fr = "Gestionnaire de liens simple"

version = "1.6.1~ynh1"

maintainers = []

[upstream]
license = "MIT"
admindoc = "https://github.com/go-shiori/shiori/wiki"
userdoc = "https://github.com/go-shiori/shiori/wiki/Usage"
code = "https://github.com/go-shiori/shiori"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/shiori"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
    
        [resources.sources.main]
        amd64.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.1/shiori_Linux_x86_64.tar.gz"
        amd64.sha256 = "db48033c3289cfb54a9436cd269b968acc4184e1e7179dfe128bcbdbe5a258e2"
        arm64.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.1/shiori_Linux_aarch64.tar.gz"
        arm64.sha256 = "f581355b4dce02cbf594bb2cfebd31867b09b4112feb09ff35a17de37181ef48"
        armhf.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.1/shiori_Linux_arm.tar.gz"
        armhf.sha256 = "017479e7835150e098a59dbf3d20bb4e5866b69e195d88d7ff45407bc1f9e05f"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^shiori_Linux_x86_64.tar.gz$"
        autoupdate.asset.arm64 = "^shiori_Linux_aarch64.tar.gz$"
        autoupdate.asset.armhf = "^shiori_Linux_arm.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "sqlite3"
