packaging_format = 2

id = "shiori"
name = "Shiori"
description.en = "Simple bookmark manager"
description.fr = "Gestionnaire de liens simple"

version = "1.6.2~ynh1"

maintainers = []

[upstream]
license = "MIT"
admindoc = "https://github.com/go-shiori/shiori/wiki"
userdoc = "https://github.com/go-shiori/shiori/wiki/Usage"
code = "https://github.com/go-shiori/shiori"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/shiori"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]
    
        [resources.sources.main]
        amd64.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.2/shiori_Linux_x86_64.tar.gz"
        amd64.sha256 = "cc707b8edf4966240f3e7e601f20e77f1fb463b932d75334df0f17aabcac0087"
        arm64.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.2/shiori_Linux_aarch64.tar.gz"
        arm64.sha256 = "fb294eaf4078983a789928bed5f3aadd3690237591356728fc191e76aa2df2f2"
        armhf.url = "https://github.com/go-shiori/shiori/releases/download/v1.6.2/shiori_Linux_arm.tar.gz"
        armhf.sha256 = "6a5ebb2f418073ce826384a3be299377ebcae7412c6abbbded05be1c9247dee5"
        in_subdir = false
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.amd64 = "^shiori_Linux_x86_64.tar.gz$"
        autoupdate.asset.arm64 = "^shiori_Linux_aarch64.tar.gz$"
        autoupdate.asset.armhf = "^shiori_Linux_arm.tar.gz$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "sqlite3"
