packaging_format = 2

id = "shiori"
name = "Shiori"
description.en = "Simple bookmark manager"
description.fr = "Gestionnaire de liens simple"

version = "1.5.3~ynh6"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
admindoc = "https://github.com/go-shiori/shiori/wiki"
userdoc = "https://github.com/go-shiori/shiori/wiki/Usage"
code = "https://github.com/go-shiori/shiori"
website = "https://github.com/go-shiori/shiori"

[integration]
yunohost = ">= 11.0.9"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/shiori"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
